### ISSUE TITLE
What is COOKIE_SECRET?

### ISSUE THREAD

**Issue by snowe2010** [the-obsidian/mc-discourse-sso#1]
I cannot find any sort of COOKIE_SECRET in the Discourse configuration settings.

**Comment by jacobwgillespie** [comment]
It's a secret value used to encode the session cookie - it can be anything you want (I personally use a random hex string like `92787547282ae938dfe43a1b52c08893e044fcbb25ee4d0e65696e11d5cc10b1`)

**Comment by jacobwgillespie** [comment]
And it doesn't have to match anything in Discourse (it's only used for the Minecraft login functionality)
