### ISSUE TITLE
Provider doesn't redirect back to discourse after authentication

### ISSUE THREAD

**Issue by snowe2010** [the-obsidian/mc-discourse-sso#3]
I'm probably missing something again, but obsidian is not redirecting back to discourse after logging in. I've tried quite a few different settings, but I'm pretty new to node.

**Comment by jacobwgillespie** [comment]
You are pressing login on Discourse, right?  You should start from Discourse, which should redirect you to the app, which should then redirect you back after login.

**Comment by snowe2010** [comment]
Solution was to put `http://` at the front of the `DISCOURSE_URL` environment variable. That took a long time to figure out though.

**Comment by jacobwgillespie** [comment]
Ah, yep - I should probably mention that in the README (personally I'm using SSL, so I've got `https://` in there).  Glad you figured it out!
